name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Label the PR
      uses: actions/github-script@v9
      with:
        script: |
          const labels = {
            API: 'api', BENCH: 'bench', BLD: 'build', BUG: 'bug',
            DEP: 'deprecation', DEV: 'development', DOC: 'documentation',
            ENH: 'enhancement', MAINT: 'maintenance', REV: 'revert',
            STY: 'style', TST: 'test', REL: 'release'
          };
          const {title, number} = context.payload.pull_request;
          const prefix = Object.keys(labels).find(key => title.startsWith(key));
          if (prefix) {
            await github.rest.issues.addLabels({
              ...context.repo,
              issue_number: number,
              labels: [labels[prefix]]
            });
          }
